# Generated by Django 3.2.6 on 2022-12-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientsaboutus',
            table='Client About Us',
        ),
    ]
