# Generated by Django 3.2.6 on 2022-12-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_clientsaboutus_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beforeafter',
            name='image_after',
            field=models.ImageField(upload_to='After_images/'),
        ),
        migrations.AlterField(
            model_name='beforeafter',
            name='image_before',
            field=models.ImageField(upload_to='Before_images/'),
        ),
        migrations.AlterField(
            model_name='clientsaboutus',
            name='image',
            field=models.ImageField(upload_to='Clients_About_Us/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(upload_to='Users_Message/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='Portfolio/'),
        ),
        migrations.AlterField(
            model_name='smiaboutus',
            name='image',
            field=models.ImageField(upload_to='Smi_about_us/'),
        ),
    ]
