# Generated by Django 3.2.6 on 2022-11-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
