# Generated by Django 3.2.6 on 2022-11-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_hotel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='day',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
