# Generated by Django 3.2.6 on 2022-11-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='day',
        ),
    ]
