# Generated by Django 3.2.6 on 2022-11-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HappyTraveler',
        ),
    ]
