# Generated by Django 3.2.6 on 2022-11-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_happytraveler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to='Destionation_Images/%Y-Year/%m-Month'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(upload_to='Hotels_Images/%Y-Year/%m-Month'),
        ),
    ]
