# Generated by Django 3.2.6 on 2022-11-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='Category_Images/%Y-Year/%m-Month'),
            preserve_default=False,
        ),
    ]
